// import the library
import { library } from "@fortawesome/fontawesome-svg-core";
import {
  faAngleUp,
  faAngleDown,
  faTrashAlt,
  faEdit,
  faLongArrowAltUp,
  faLongArrowAltDown,
  faBug,
  faBook,
  faTasks,
  faCheckSquare,
  faBookmark,
  faMarker,
  faArrowLeft,
  faWindowClose,
  faEllipsisV,
  faCheck,
  faUser,
  faLockOpen,
  faCircle,
  faChevronRight,
  faFile,
} from "@fortawesome/free-solid-svg-icons";

library.add(
  faAngleUp,
  faAngleDown,
  faTrashAlt,
  faEdit,
  faLongArrowAltUp,
  faLongArrowAltDown,
  faBug,
  faBook,
  faTasks,
  faCheckSquare,
  faBookmark,
  faMarker,
  faArrowLeft,
  faWindowClose,
  faEllipsisV,
  faCheck,
  faUser,
  faLockOpen,
  faCircle,
  faChevronRight,
  faFile
);
